[package]
name = "gerenciador_de_tarefas"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
